### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by bryglen** [SymfonyId/RehatBundle#2]
How to use this btw?

Im doing in my controller

``` php
return $this->post($request, new EventType(), new Event());
```

my EventType is

``` php
class EventType extends Symfony\Component\Form\AbstractType
```

I got error

```
Catchable Fatal Error: Argument 2 passed to Symfonian\Indonesia\RehatBundle\Controller\RehatController::post() must be an instance of Symfony\Component\Form\FormInterface, instance of RestBundle\Form\EventType given
```

**Comment by ad3n** [comment]
Your EventType is not extends from AbstractType

`class EventType extends AbstractType`

**Comment by bryglen** [comment]
any docs how to use your awesome plugin? thanks

**Comment by ad3n** [comment]
https://github.com/ihsanudin/RehatSkeleton/blob/master/src/AppBundle/Api/GroupApiController.php

You can read the controller example from skeleton

**Comment by bryglen** [comment]
awesome, thanks
